export const FETCH_TWEETS = "FETCH_TWEETS";
export const FETCH_TWEETS_SUCCESS = "FETCH_TWEETS_SUCCESS";
export const FETCH_TWEETS_FAIL = "FETCH_TWEETS_FAIL";

export const SEND_TWEET = "SEND_TWEET";
export const SEND_TWEET_SUCCESS = "SEND_TWEET_SUCCESS";
export const SEND_TWEET_FAIL = "SEND_TWEET_FAIL";

export const LIKE_TWEET = "LIKE_TWEET";
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAIL = "LIKE_TWEET_FAIL";